defmodule Screens.Headsigns.Data do
  @moduledoc """
  Module for storing headsign abbreviations.

  The first item in the list is the default headsign name we show on Screens,
  and additional items are alternative shortened names that might be shown.

  Headsigns without any abbreviations aside from their
  default names (i.e. Airport) are not included in this map.

  See the generate_headsign_abbreviations.exs script to see how to generate this data in bulk.
  """

  @headsign_abbreviations %{
    "Allston Street" => ["Allston Street", "Allston St"],
    "Babcock Street" => ["Babcock Street", "Babcock St"],
    "Back of the Hill" => ["Back of the Hill", "Back of Hill", "Back o'Hill"],
    "Ball Square" => ["Ball Square", "Ball Sq"],
    "Beaconsfield" => ["Beaconsfield", "B'consfield"],
    "Bellingham Square" => ["Bellingham Square", "Bellingham Sq"],
    "Blandford Street" => ["Blandford Street", "Blandford St", "Blandford"],
    "Boston College" => ["Boston College", "Boston Coll"],
    "Boston University Central" => ["Boston University Central", "BU Central"],
    "Boston University East" => ["Boston University East", "BU East"],
    "Boston University West" => ["Boston University West", "BU West"],
    "Brandon Hall" => ["Brandon Hall", "Brandon Hll"],
    "Brigham Circle" => ["Brigham Circle", "Brigham Cir"],
    "Brookline Hills" => ["Brookline Hills", "B'kline Hls"],
    "Brookline Village" => ["Brookline Village", "Brookline Vill", "B'kline Vil"],
    "Capen Street" => ["Capen Street", "Capen St"],
    "Cedar Grove" => ["Cedar Grove", "Cedar Grv"],
    "Central Avenue" => ["Central Avenue", "Central Ave"],
    "Charlestown Navy Yard" => ["Charlestown Navy Yard", "Charlestown"],
    "Chestnut Hill" => ["Chestnut Hill", "Chestnut Hl"],
    "Chestnut Hill Avenue" => ["Chestnut Hill Ave", "Chestnut Hl"],
    "Chiswick Road" => ["Chiswick Rd"],
    "Cleveland Circle" => ["Cleveland Circle", "Cleveland Cir", "Clvlnd Cir"],
    "Community College" => ["Community College", "Community Coll", "Com College"],
    "Coolidge Corner" => ["Coolidge Corner", "Coolidge Cn"],
    "Dean Road" => ["Dean Road", "Dean Rd"],
    "Design Center" => ["Design Center", "Design Ctr"],
    "Downtown Crossing" => ["Downtown Crossing", "Downtown Xng", "Downt'n Xng"],
    "East Berkeley St" => ["East Berkeley Street", "East Berkeley St", "E Berkeley St"],
    "East Somerville" => ["East Somerville", "E Somerville", "E Somervlle"],
    "Englewood Avenue" => ["Englewood Avenue", "Englewood Ave", "Englew'd Av"],
    "Fairbanks Street" => ["Fairbanks Street", "Fairbanks St", "Fairbanks"],
    "Fenwood Road" => ["Fenwood Road", "Fenwood Rd"],
    "Fields Corner" => ["Fields Corner", "Fields Cnr"],
    "Forest Hills" => ["Forest Hills", "Frst Hills"],
    "Gilman Square" => ["Gilman Square", "Gilman Sq"],
    "Government Center" => ["Government Ctr", "Gov’t Center", "Gov't Ctr"],
    "Green Street" => ["Green Street", "Green St"],
    "Griggs Street" => ["Griggs Street", "Griggs St"],
    "Harvard Avenue" => ["Harvard Avenue", "Harvard Ave"],
    "Hawes Street" => ["Hawes Street", "Hawes St"],
    "Heath Street" => ["Heath Street", "Heath St"],
    "Houghs Neck via Germantown" => ["Houghs Neck via Germntwn"],
    "Houghs Neck via McGrath & Germantown" => ["Houghs Neck via McGth & Gtwn"],
    "Hynes Convention Center" => ["Hynes Convention Center", "Hynes"],
    "Jackson Square" => ["Jackson Sq"],
    "Kent Street" => ["Kent Street", "Kent St"],
    "Longwood Medical Area" => ["Longwood Medical Area", "Longwood Med", "Lngwd Med"],
    "Magoun Square" => ["Magoun Square", "Magoun Sq"],
    "Malden Center" => ["Malden Center", "Malden Ctr"],
    "Malden via Square One Mall & Kennedy Dr" => ["Malden via Square One Mall & Kndy Dr"],
    "Massachusetts Avenue" => ["Mass Ave"],
    "Medford/Tufts" => ["Medford/Tufts", "Medfd/Tufts"],
    "Mission Park" => ["Mission Park", "Mission Pk"],
    "Museum of Fine Arts" => ["Museum of Fine Arts", "MFA"],
    "Needham Heights" => ["Needham Heights", "Needham Hts"],
    "Newton Centre" => ["Newton Centre", "Newton Ctr"],
    "Newton Highlands" => ["Newton Highlands", "Newton Hlnd"],
    "North Quincy" => ["North Quincy", "N Quincy"],
    "North Station" => ["North Station", "North Sta"],
    "Northeastern" => ["Northeastern University", "Northeastern", "Northeast'n"],
    "Orient Heights" => ["Orient Heights", "Orient Hts"],
    "Packard's Corner" => ["Packards Corner", "Packards Cn"],
    "Park Street" => ["Park Street", "Park St"],
    "Quincy Adams" => ["Quincy Adams", "Quincy Adms"],
    "Quincy Center" => ["Quincy Center", "Quincy Ctr"],
    "Revere Beach" => ["Revere Beach", "Revere Bch"],
    "Roxbury Crossing" => ["Roxbury Crossing", "Roxbury Xng"],
    "Saint Mary's Street" => ["St. Mary's Street", "St. Mary's St", "St. Mary's"],
    "Saint Paul Street" => ["St. Paul Street", "St. Paul St"],
    "Saugus Center via Kennedy Dr & Square One Mall" => ["Saugus Center via Kndy Dr & Square One"],
    "Science Park/West End" => ["Science Park/West End", "Science Park", "Science Pk"],
    "Silver Line Way" => ["Silver Line Way"],
    "South Station" => ["South Station", "South Sta"],
    "South Street" => ["South Street", "South St"],
    "Suffolk Downs" => ["Suffolk Downs", "Suffolk Dns"],
    "Sullivan Square" => ["Sullivan Square", "Sullivan Sq"],
    "Summit Avenue" => ["Summit Avenue", "Summit Ave"],
    "Sutherland Road" => ["Sutherland Road", "Sutherland Rd", "Sutherland"],
    "Tappan Street" => ["Tappan Street", "Tappan St"],
    "Tufts Medical Center" => ["Tufts Medical Center", "Tufts Medical", "Tufts Med"],
    "Union Square" => ["Union Square", "Union Sq"],
    "Valley Road" => ["Valley Road", "Valley Rd"],
    "Warren Street" => ["Warren Street", "Warren St"],
    "Washington Square" => ["Washington Square", "Washington Sq", "Wshngtn Sq"],
    "Washington Street" => ["Washington Street", "Washington St", "Wshngtn St"],
    "Washington St & Pleasant St Weymouth" => ["Washington St & Plsnt St Weymouth"],
    "Wickford Junction" => ["Wickford Junction", "Wickford Jct"],
    "Woodland Rd via Gateway Center" => ["Woodland Rd via Gatew'y Center"],
    "Worcester Square" => ["Worcester Square", "Worcester Sq"],
    "World Trade Center" => ["World Trade Center", "World Trade Ctr"]
  }

  @word_abbreviations %{
    "Avenue" => "Ave",
    "Boulevard" => "Blvd",
    "Center" => "Ctr",
    "Circle" => "Cir",
    "Cleveland" => "Clvlnd",
    "College" => "Coll",
    "Corner" => "Cn",
    "Court" => "Ct",
    "Drive" => "Dr",
    "East" => "E",
    "Express" => "Exp",
    "Government" => "Gov't",
    "Heights" => "Hts",
    "Landing" => "Ldg",
    "Lane" => "Ln",
    "Limited" => "Ltd",
    "One" => "1",
    "Park" => "Pk",
    "Parkway" => "Pkwy",
    "Place" => "Pl",
    "Point" => "Pt",
    "Road" => "Rd",
    "Saint" => "St.",
    "South" => "So",
    "Square" => "Sq",
    "Station" => "Stn",
    "Street" => "St",
    "Terrace" => "Ter",
    "Village" => "Vill",
    "Washington" => "Wash",
    "Way" => "Wy",
    "West" => "W"
  }

  def abbreviations, do: @headsign_abbreviations

  def word_abbreviations, do: @word_abbreviations
end
