version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ex_aws
    versions:
    - 2.1.8
    - 2.1.9
    - 2.2.0
  - dependency-name: timex
    versions:
    - 3.7.0
    - 3.7.2
    - 3.7.3
  - dependency-name: hackney
    versions:
    - 1.17.1
    - 1.17.2
    - 1.17.3
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.4
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: ts-jest
    versions:
    - 26.5.4
  - dependency-name: react
    versions:
    - 17.0.1
    - 17.0.1
    - 17.0.2
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
  - dependency-name: core-js
    versions:
    - 3.8.3
    - 3.9.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.16
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: react-dom
    versions:
    - 17.0.1
