version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 5
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 5
    groups:
      mix-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: npm
    directory: "/assets"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 5
    groups:
      npm-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
          - "@eslint*"
      react:
        patterns:
          - "react*"
          - "@types/react*"
      testing-tools:
        patterns:
          - "ts-jest"
          - "jest*"
          - "@jest*"
      babel:
        patterns:
          - "babel*"
          - "@babel*"
      webpack:
        patterns:
          - "webpack*"
          - "*webpack-plugin"
          - "@svgr/webpack"
          - "@types/webpack-env"
          - "*-loader"
          - "terser*"
      polyfills:
        patterns:
          - "core-js*"
          - "regenerator-runtime"
          - "whatwg-fetch"
      moment:
        patterns:
          - "moment*"
