name: Setup
description: Installs tools and dependencies

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: asdf-cache
      with:
        path: ~/.asdf
        key: asdf-${{ hashFiles('.tool-versions') }}
    - uses: asdf-vm/actions/install@v3
      if: steps.asdf-cache.outputs.cache-hit != 'true'
    - uses: mbta/actions/reshim-asdf@v2
      if: steps.asdf-cache.outputs.cache-hit == 'true'
    - name: Elixir tools
      if: steps.asdf-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mix local.rebar --force
        mix local.hex --force

    - uses: actions/cache@v4
      id: ex-deps-cache
      with:
        path: |
          _build
          deps
        key: ex-deps-${{ hashFiles('.tool-versions', '**/mix.lock') }}
    - name: Elixir dependencies
      if: steps.ex-deps-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mix deps.get
        mix deps.compile

    - uses: actions/cache@v4
      id: js-deps-cache
      with:
        path: assets/node_modules
        key: js-deps-${{ hashFiles('.tool-versions', '**/package-lock.json') }}
    - name: JS dependencies
      if: steps.js-deps-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci --prefix assets
