name: Asana integration
on: 
  pull_request:
    types: [edited, opened]

permissions:
  pull-requests: read # Needed to read Asana ticket info from PR description

jobs:
  asana:
    uses: mbta/workflows/.github/workflows/asana.yml@ba8d62bff3a4aa0df22eb2d6a1ce7ad4fb2eac1a # v5.1.1
    with:
      attach-pr: true
      trigger-phrase: "\\*\\*Asana task\\*\\*:"
    secrets:
      asana-token: ${{ secrets.ASANA_SECRET_FOR_INSURIFY_ACTION }}
      github-secret: ${{ secrets.ASANA_GITHUB_INTEGRATION_SECRET }}
