name: Asana integration
on: 
  pull_request:
    types: [edited, opened]

permissions:
  pull-requests: read # Needed to read Asana ticket info from PR description

jobs:
  asana:
    uses: mbta/workflows/.github/workflows/asana.yml@c76e5ccd9556fbea52bc41548f7ceed5985ad775 # v5.1.0
    with:
      attach-pr: true
      trigger-phrase: "\\*\\*Asana task\\*\\*:"
    secrets:
      asana-token: ${{ secrets.ASANA_SECRET_FOR_INSURIFY_ACTION }}
      github-secret: ${{ secrets.ASANA_GITHUB_INTEGRATION_SECRET }}
