name: Asana integration
on: 
  pull_request:
    types: [opened, reopened]

jobs:
  asana:
    uses: mbta/workflows/.github/workflows/asana.yml@v4
    with:
      attach-pr: true
      trigger-phrase: "\\*\\*Asana task\\*\\*:"
    secrets:
      asana-token: ${{ secrets.ASANA_SECRET_FOR_INSURIFY_ACTION }}
      github-secret: ${{ secrets.ASANA_GITHUB_INTEGRATION_SECRET }}
