name: Asana integration
on: 
  pull_request:
    types: [edited, opened]

permissions: {}

jobs:
  asana:
    uses: mbta/workflows/.github/workflows/asana.yml@ead2d40fcc0c546bd6f099a6d8fcd9f9950eab03 # v5.0.0
    with:
      attach-pr: true
      trigger-phrase: "\\*\\*Asana task\\*\\*:"
    secrets:
      asana-token: ${{ secrets.ASANA_SECRET_FOR_INSURIFY_ACTION }}
      github-secret: ${{ secrets.ASANA_GITHUB_INTEGRATION_SECRET }}
