name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - docs/**
      - "*.md"
      - LICENSE

permissions: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  MIX_ENV: test

jobs:
  build-elixir:
    name: Build and Test Elixir
    runs-on: ubuntu-latest
    env:
      DATABASE_PASSWORD: postgres
      DATABASE_USER: postgres
      DATABASE_NAME: screens_test
      DATABASE_HOST: localhost
    services:
      postgres:
        image: postgres@sha256:1961f96e6029a02c3812d7cb329a3b03a3ac2bb067058dec17b0f5596aca9296
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ${{env.DATABASE_PASSWORD}}
          POSTGRES_USER: ${{env.DATABASE_USER}}
          POSTGRES_DB: ${{env.DATABASE_NAME}}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - name: Elixir Compile (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Elixir Tests
        run: mix test

  ex-credo:
    name: Elixir Credo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: mix credo.ci

  ex-dialyzer:
    name: Elixir Dialyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - uses: mbta/actions/dialyzer@788f8e264e9ebb1b76b927c89e6466d5a162be80 # v2.24

  ex-format:
    name: Elixir Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: mix format --check-formatted

  js-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - working-directory: ./assets
        run: npm run deploy

  js-format:
    name: Frontend Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - working-directory: ./assets
        run: npm run format:check

  js-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - working-directory: ./assets
        run: npm run lint:errors

  js-styles:
    name: Frontend Styles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - working-directory: ./assets
        run: npm run styles:check

  js-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - working-directory: ./assets
        run: npm test

  js-types:
    name: Frontend Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - working-directory: ./assets
        run: npx --no tsc

  js-unused:
    name: Frontend Unused
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - working-directory: ./assets
        run: npm run unused
