name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: dev
  push:
    branches: ["main"]

jobs:
  sentry-upload:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - working-directory: ./assets
        run: npm run deploy
  call-workflow:
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@v4
    with:
      app-name: screens
      environment: ${{ github.event.inputs.environment || 'dev' }}
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
  refresh:
    needs: call-workflow
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Create LAST_DEPLOY and upload to S3
        run: |
          touch LAST_DEPLOY
          echo "This file's modified date is used by Screens app to determine when the last successful deploy happened" > LAST_DEPLOY
          aws s3 cp LAST_DEPLOY s3://mbta-screens/screens-${{ github.event.inputs.environment || 'dev' }}/
