name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: dev
  push:
    branches: ["main"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
  cancel-in-progress: true

jobs:
  sentry-upload:
    name: "Upload sourcemaps to Sentry"
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }} # zizmor: ignore[secrets-outside-env] - TODO: Move to a dedicated environment
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }} # zizmor: ignore[secrets-outside-env] - TODO: Move to a dedicated environment
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }} # zizmor: ignore[secrets-outside-env] - TODO: Move to a dedicated environment
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - working-directory: ./assets
        run: npm run deploy
  call-workflow:
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@ead2d40fcc0c546bd6f099a6d8fcd9f9950eab03 # v5.0.0
    with:
      app-name: screens
      environment: ${{ github.event.inputs.environment || 'dev' }}
    permissions: {
      contents: read, # Needed to check out the repository
      id-token: write # Needed to authenticate against AWS
    }
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
  refresh:
    name: "Update last successful deploy timestamp"
    needs: call-workflow
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to authenticate with AWS
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # zizmor: ignore[secrets-outside-env] - TODO: Move to a dedicated environment
          aws-region: us-east-1
      - name: Create LAST_DEPLOY and upload to S3
        run: |
          touch LAST_DEPLOY
          echo "This file's modified date is used by Screens app to determine when the last successful deploy happened" > LAST_DEPLOY
          aws s3 cp LAST_DEPLOY s3://mbta-screens/screens-${BUCKET_SUFFIX}/
        env:
          BUCKET_SUFFIX: ${{ github.event.inputs.environment || 'dev' }}
