name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: dev
  push:
    branches: ["main"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
  cancel-in-progress: true

jobs:
  sentry-upload:
    name: "Upload sourcemaps to Sentry"
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }} # zizmor: ignore[secrets-outside-env] - TODO: Move to a dedicated environment
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }} # zizmor: ignore[secrets-outside-env] - TODO: Move to a dedicated environment
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }} # zizmor: ignore[secrets-outside-env] - TODO: Move to a dedicated environment
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - working-directory: ./assets
        run: npm run deploy
  call-workflow:
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@ba8d62bff3a4aa0df22eb2d6a1ce7ad4fb2eac1a # v5.1.1
    with:
      app-name: screens
      environment: ${{ github.event.inputs.environment || 'dev' }}
    permissions: {
      contents: read, # Needed to check out the repository
      id-token: write # Needed to authenticate against AWS
    }
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
